FasterMate/Controllers/GroupController.cs
namespace FasterMate.Controllers
{
    using FasterMate.Core.Contracts;
    using FasterMate.ViewModels.Group;
    using Microsoft.AspNetCore.Mvc;
    using System.Security.Claims;

    public class GroupController : BaseController
    {
        private readonly IGroupService groupService;
        private readonly IProfileService profileService;

        private readonly IWebHostEnvironment webHost;

        public GroupController(
            IGroupService _groupService,
            IProfileService _profileService,
            IWebHostEnvironment _webHost)
        {
            groupService = _groupService;
            profileService = _profileService;

            webHost = _webHost;
        }

        public IActionResult LetsChat(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var isMember = groupService.IsMemberOfTheGroup(id, profileId);

            if (isMember)
            {
                var viewModel = groupService.GetGroupById(id);
                viewModel.ProfileId = profileId;

                return View(viewModel);
            }

            return BadRequest();
        }

        public IActionResult Create()
        {
            var viewModel = new CreateGroupViewModel();

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateGroupViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var groupId = await groupService.CreateAsync(profileId, input, $"{webHost.WebRootPath}\\img\\groups");

            return RedirectToAction(nameof(LetsChat), new { id = groupId });
        }

        public IActionResult MyGroups()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var viewModel = groupService.GetProfileGroups(profileId).ToList();
            foreach (var group in viewModel)
            {
                group.IsOwner = groupService.IsOwnerOfTheGroup(group.Id, profileId);
            }

            return View(viewModel);
        }

        public IActionResult Members(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var viewModel = new GroupMemberViewModel()
            {
                Id = id,
                Members = groupService.GetMembers(id, profileId)
            };


            return View(viewModel);
        }

        public IActionResult Edit(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var isOwner = groupService.IsOwnerOfTheGroup(id, profileId);

            if (isOwner)
            {
                var inputModel = groupService.GetGroupForEdit(id);

                return View(inputModel);
            }

            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditGroupViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var isOwner = groupService.IsOwnerOfTheGroup(input.Id, profileId);

            if (isOwner)
            {
                await groupService.UpdateAsync(input, $"{webHost.WebRootPath}\\img\\groups");
            }

            return RedirectToAction(nameof(MyGroups));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var isOwner = groupService.IsOwnerOfTheGroup(id, profileId);

            if (isOwner)
            {
                await groupService.DeleteGroupAsync(id);
            }

            return RedirectToAction(nameof(MyGroups));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveMember(string id, string removeId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var isOwner = groupService.IsOwnerOfTheGroup(id, profileId);

            if (isOwner)
            {
                await groupService.RemoveAsync(id, removeId);
            }

            return RedirectToAction(nameof(MyGroups), new { id });
        }

        public IActionResult AddMember(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var isOwner = groupService.IsOwnerOfTheGroup(id, profileId);

            if (isOwner)
            {
                var viewModel = new FollowersToInviteViewModel()
                {
                    Id = id,
                    Followers = groupService.GetFollowersOfProfile(profileId, id)
                };

                return View(viewModel);
            }

            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> AddMember(string id, string addingId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var isOwner = groupService.IsOwnerOfTheGroup(id, profileId);

            if (isOwner)
            {
                await groupService.AddMemberAsync(addingId, id);

                return RedirectToAction(nameof(AddMember), new { id });
            }

            return BadRequest();
        }
    }
}

FasterMate/Controllers/OfferController.cs
namespace FasterMate.Controllers
{
    using System.Security.Claims;

    using FasterMate.Core.Constants;
    using FasterMate.Core.Contracts;
    using FasterMate.ViewModels.Offer;

    using Microsoft.AspNetCore.Mvc;

    public class OfferController : BaseController
    {
        private readonly IProfileService profileService;
        private readonly IOfferService offerService;

        public OfferController(
            IProfileService _profileService,
            IOfferService _offerService)
        {
            profileService = _profileService;
            offerService = _offerService;
        } 

        public IActionResult BookAFlight()
        {
            var offers = offerService.GetAllOffers();

            return View(offers);
        }

        public IActionResult MyFlights()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var viewModel = offerService.BookedOffersOfProfile(profileId);

            return View(viewModel);
        }

        public IActionResult AddAnOffer()
        {
            var viewModel = new CreateOfferViewModel();

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddAnOffer(CreateOfferViewModel input)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            if (!ModelState.IsValid)
            {
                return View(input);
            }

            if (DateTime.Parse(input.DepartureTime) < DateTime.Now)
            {
                ViewData[MessageConstant.ErrorMessage] = "Your departure time is invalid!";
                return View(input);
            }

            if (DateTime.Parse(input.ArrivalTime) < DateTime.Now)
            {
                ViewData[MessageConstant.ErrorMessage] = "Your arrival time is invalid!";
                return View(input);
            }

            var offer = await offerService.CreateAsync(input, profileId);
            if (offer == false)
            {
                ViewData[MessageConstant.ErrorMessage] = "Arrival Time cannot be before the Departure Time!";
                return View(input);
            }

            return RedirectToAction(nameof(BookAFlight));
        }

        public async Task<IActionResult> BookTicket(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            await offerService.CreateProfileOfferAsync(id, profileId);
            
            return RedirectToAction(nameof(BookAFlight));
        }
    }
}

FasterMate/Controllers/PostController.cs
namespace FasterMate.Controllers
{
    using System.Security.Claims;

    using FasterMate.Core.Contracts;
    using FasterMate.ViewModels.Comment;
    using FasterMate.ViewModels.Post;

    using Microsoft.AspNetCore.Mvc;

    public class PostController : BaseController
    {
        private readonly IProfileService profileService;
        private readonly IPostService postService;
        private readonly ICommentService commentService;

        private readonly IWebHostEnvironment webHost;

        public PostController(
            IProfileService _profileService,
            IPostService _postService,
            ICommentService _commentService,
            IWebHostEnvironment _webHost)
        {
            profileService = _profileService;
            postService = _postService;
            commentService = _commentService;

            webHost = _webHost;
        }

        public IActionResult CreatePost()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var viewModel = new CreatePostViewModel
            {
                ReturnId = profileId
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(CreatePostViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            await postService.CreateAsync(profileId, input, $"{webHost.WebRootPath}\\img\\posts");

            return RedirectToAction("UserProfile", "Profile", new { id = profileId });
        }

        public IActionResult SeePost(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var post = postService.RenderSinglePost(id, profileId);

            return View(post);
        }

        [HttpPost]
        public async Task<IActionResult> SeePost(AddCommentViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            await commentService.AddAsync(profileId, input);

            return RedirectToAction(nameof(SeePost), new { id = input.PostId });
        }

        public async Task<IActionResult> LikePost(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            await postService.LikePostAsync(profileId, id);

            return RedirectToAction(nameof(SeePost), new { id });
        }

        public async Task<IActionResult> DeletePost(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            await postService.DeleteAsync(profileId, id);

            return RedirectToAction("UserProfile", "Profile", new { id = profileId });
        }

        public async Task<IActionResult> DeleteComment(string id)
        {
            var postId = await commentService.DeleteAsync(id);

            return RedirectToAction(nameof(SeePost), new { id = postId });
        }
    }
}

FasterMate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css" />
    <link rel="stylesheet" href="~/css/adminlte.min.css" />
    <link rel="stylesheet" href="~/plugins/toastr/toastr.min.css" />
    <script src="~/lib//microsoft/signalr/dist/browser/signalr.min.js" asp-append-version="true"></script>

    <link rel="shortcut icon" type="image/x-icon" href=@Url.Action("~/favicon.ico") />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @await RenderSectionAsync("Head", false)
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <aside class="main-sidebar sidebar-dark-primary elevation-4" style="position:fixed;">
            <a href="/" class="brand-link">
                <img src="~/img/common/logo.png" alt="FasterMate Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">FasterMate</span>
            </a>

            <div class="sidebar">
                <partial name="_LoginPartial" />

                <partial name="_MainMenu" />
            </div>
        </aside>

        <div class="content-wrapper mt-3">
            <div class="content">
                <div class="container-fluid">
                    <partial name="_CookieConsentPartial" />
                    @RenderBody()
                </div>
            </div>
        </div>

        <footer class="main-footer">
            <div class="float-right d-none d-sm-inline">
                Let's travel!
            </div>
            <strong>Copyright &copy; @DateTime.Now.Year <a href="/">FasterMate</a>.</strong> All rights reserved.
        </footer>
    </div>
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/adminlte.min.js"></script>
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <partial name="_UserMessages" />
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

FasterMate/Views/Shared/_LayoutOld.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FasterMate</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FasterMate.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FasterMate</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FasterMate
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FasterMate/Views/Shared/_MainMenu.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        @if (!SignInManager.IsSignedIn(User))
        {
            <li class="nav-item">
                <a class="nav-link" asp-area="Identity" asp-page="/Account/Register" asp-route-returnUrl="@Url.Page("/", new { area = "" })" method="post">
                    <i class="nav-icon fas fa-user-plus"></i>
                    <p>
                        Register
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="Identity" asp-page="/Account/Login" asp-route-returnUrl="@Url.Page("/", new { area = "" })" method="post">
                    <i class="nav-icon fas fa-sign-in-alt"></i>
                    <p>
                        Login
                    </p>
                </a>
            </li>
        }
        else
        {
            @if (this.User.IsInRole("Administrator"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-area="Administrator" asp-controller="Home" asp-action="Index">
                        <i class="nav-icon fas fa-fingerprint"></i>
                        <p>
                            Administrator
                        </p>
                    </a>
                </li>
            }

            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="nav-icon fas fa-home"></i>
                    <p>
                        Home
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Search">
                    <i class="nav-icon fas fa-search"></i>
                    <p>
                        Search
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Post" asp-action="CreatePost">
                    <i class="nav-icon fas fa-clipboard"></i>
                    <p>
                        Create a Post
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Offer" asp-action="BookAFlight">
                    <i class="nav-icon fas fa-plane-departure"></i>
                    <p>
                        Book a Flight?
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Offer" asp-action="MyFlights">
                    <i class="nav-icon fas fa-ticket-alt"></i>
                    <p>
                        My Flights
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Group" asp-action="MyGroups">
                    <i class="nav-icon fas fa-users"></i>
                    <p>
                        Chat Groups
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Page("/", new { area = "" })" method="post">
                    <i class="nav-icon fas fa-sign-out-alt"></i>
                    <p>
                        Logout
                    </p>
                </a>
            </li>
        }
    </ul>
</nav>

FasterMate/Views/Shared/_UserMessages.cshtml
@using FasterMate.Core.Constants

@if (ViewData[MessageConstant.ErrorMessage] != null)
{
    <script>
        $(function() {
            toastr.error('@ViewData[MessageConstant.ErrorMessage]?.ToString()')
        })
    </script>
}

@if (ViewData[MessageConstant.WarningMessage] != null)
{
    <script>
        $(function() {
            toastr.warning('@ViewData[MessageConstant.WarningMessage]?.ToString()')
        })
    </script>
}

@if (ViewData[MessageConstant.SuccessMessage] != null)
{
    <script>
        $(function() {
            toastr.success('@ViewData[MessageConstant.SuccessMessage]?.ToString()')
        })
    </script>
}