FasterMate/Controllers/GroupController.cs
namespace FasterMate.Controllers
{
    using FasterMate.Core.Contracts;
    using FasterMate.ViewModels.Group;
    using Microsoft.AspNetCore.Mvc;
    using System.Security.Claims;

    public class GroupController : BaseController
    {
        private readonly IGroupService groupService;
        private readonly IProfileService profileService;

        private readonly IWebHostEnvironment webHost;

        public GroupController(
            IGroupService _groupService,
            IProfileService _profileService,
            IWebHostEnvironment _webHost)
        {
            groupService = _groupService;
            profileService = _profileService;

            webHost = _webHost;
        }

        public IActionResult LetsChat(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var isMember = groupService.IsMemberOfTheGroup(id, profileId);

            if (isMember)
            {
                var viewModel = groupService.GetGroupById(id);
                viewModel.ProfileId = profileId;

                return View(viewModel);
            }

            return BadRequest();
        }

        public IActionResult Create()
        {
            var viewModel = new CreateGroupViewModel();

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateGroupViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var groupId = await groupService.CreateAsync(profileId, input, $"{webHost.WebRootPath}\\img\\groups");

            return RedirectToAction(nameof(LetsChat), new { id = groupId });
        }

        public IActionResult MyGroups()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var viewModel = groupService.GetProfileGroups(profileId).ToList();
            foreach (var group in viewModel)
            {
                group.IsOwner = groupService.IsOwnerOfTheGroup(group.Id, profileId);
            }

            return View(viewModel);
        }

        public IActionResult Members(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var viewModel = new GroupMemberViewModel()
            {
                Id = id,
                Members = groupService.GetMembers(id, profileId)
            };


            return View(viewModel);
        }

        public IActionResult Edit(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var isOwner = groupService.IsOwnerOfTheGroup(id, profileId);

            if (isOwner)
            {
                var inputModel = groupService.GetGroupForEdit(id);

                return View(inputModel);
            }

            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditGroupViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var isOwner = groupService.IsOwnerOfTheGroup(input.Id, profileId);

            if (isOwner)
            {
                await groupService.UpdateAsync(input, $"{webHost.WebRootPath}\\img\\groups");
            }

            return RedirectToAction(nameof(MyGroups));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var isOwner = groupService.IsOwnerOfTheGroup(id, profileId);

            if (isOwner)
            {
                await groupService.DeleteGroupAsync(id);
            }

            return RedirectToAction(nameof(MyGroups));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveMember(string id, string removeId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var isOwner = groupService.IsOwnerOfTheGroup(id, profileId);

            if (isOwner)
            {
                await groupService.RemoveAsync(id, removeId);
            }

            return RedirectToAction(nameof(MyGroups), new { id });
        }

        public IActionResult AddMember(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var isOwner = groupService.IsOwnerOfTheGroup(id, profileId);

            if (isOwner)
            {
                var viewModel = new FollowersToInviteViewModel()
                {
                    Id = id,
                    Followers = groupService.GetFollowersOfProfile(profileId, id)
                };

                return View(viewModel);
            }

            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> AddMember(string id, string addingId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var isOwner = groupService.IsOwnerOfTheGroup(id, profileId);

            if (isOwner)
            {
                await groupService.AddMemberAsync(addingId, id);

                return RedirectToAction(nameof(AddMember), new { id });
            }

            return BadRequest();
        }
    }
}

FasterMate/Controllers/ProfileController.cs
namespace FasterMate.Controllers
{
    using FasterMate.Core.Contracts;
    using FasterMate.ViewModels.Profile;
    using Microsoft.AspNetCore.Mvc;
    using System.Security.Claims;

    public class ProfileController : BaseController
    {
        private readonly IProfileService profileService;
        private readonly ICountryService countryService;

        private readonly IWebHostEnvironment webHost;

        public ProfileController(
            IProfileService _profileService,
            ICountryService _countryService, 
            IWebHostEnvironment _webHost)
        {
            profileService = _profileService;
            countryService = _countryService;

            webHost = _webHost;
        }

        public IActionResult UserProfile(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            var viewModel = profileService.RenderProfile(id, profileId);

            if (viewModel == null)
            {
                return NotFound();
            }

            viewModel.IsOwner = profileId == id;

            return View(viewModel);
        }

        public IActionResult Edit()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = profileService.GetByUserId(userId);
            var editViewModel = profileService.GetEditViewModel(user);

            return View(editViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditProfileViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            try
            {
                await profileService.UpdateAsync(userId, input, $"{webHost.WebRootPath}\\img\\users");
            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError(string.Empty, ae.Message);
                return View(input);
            }

            return RedirectToAction(nameof(UserProfile), new { input.Id });
        }
        
        public async Task<IActionResult> Follow(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var profileId = profileService.GetId(userId);

            await profileService.FollowProfileAsync(id, profileId);

            return RedirectToAction(nameof(UserProfile), new { id });
        }
    }
}

FasterMate/Views/Group/AddMember.cshtml
@model FollowersToInviteViewModel
@{
    ViewData["Title"] = "Add Member";
}

<h2 class="text-center display-4 mt-2">Followers</h2>
@if (@Model.Followers.Count() == 0)
{
    <h2 class="text-center display-4 mt-2">You do not follow anyone!</h2>
}
else
{
    @foreach (var member in @Model.Followers)
    {
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="card card-widget widget-user mt-2">

                    <div class="widget-user-header bg-primary">
                        <a asp-action="UserProfile" asp-controller="Profile" asp-route-id="@member.ProfileId" class="widget-user-username">@member.Name</a>
                        <h5 class="widget-user-desc">&commat;@member.Username</h5>
                    </div>
                    <div class="widget-user-image">
                        @if (!string.IsNullOrWhiteSpace(member.ImagePath))
                        {
                            <img class="profile-user-img img-fluid img-circle" src="~/img/users/@member.ImagePath" alt="User profile picture">
                        }
                        else
                        {
                            <img class="profile-user-img img-fluid img-circle" src="~/img/common/default-male.png" alt="User profile picture">
                        }
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="description-block">
                                    @if (member.IsParticipating)
                                    {
                                        <h5 class="description-header">Already in the group</h5>
                                    }
                                    else
                                    {
                                        <form method="post" asp-action="AddMember" asp-route-id="@Model.Id" asp-route-addingId="@member.ProfileId">
                                            <button class="btn btn-primary">Add To Group</button>
                                        </form>
                                    }
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    }
}

FasterMate/Views/Group/Create.cshtml
@model CreateGroupViewModel
@{
    ViewData["Title"] = "Create Group";
}
<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Create a Group</h3>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Image"></label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input asp-for="Image" class="custom-file-input">
                                <label class="custom-file-label" asp-for="Image">Upload the file...</label>
                            </div>
                        </div>
                        <span asp-validation-for="Image" class="text-danger"></span>
                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

FasterMate/Views/Group/Edit.cshtml
@model EditGroupViewModel
@{
    ViewData["Title"] = "Edit Group";
}
<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Edit a Group</h3>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Image"></label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input asp-for="Image" class="custom-file-input">
                                <label class="custom-file-label" asp-for="Image">Upload the file...</label>
                            </div>
                        </div>
                        <span asp-validation-for="Image" class="text-danger"></span>
                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Edit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

FasterMate/Views/Group/LetsChat.cshtml
@model GroupViewModel
@{
    this.ViewData["Title"] = $"{Model.Name}";
}
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="card card-primary card-outline direct-chat direct-chat-primary">
            <div class="card-header">
                <h3 class="text-center display-5">@Model.Name</h3>
            </div>

            <div class="card-body">
                <div class="direct-chat-messages">
                    @foreach (var message in Model.Messages.OrderBy(x => x.CreatedOn))
                    {
                        <div class="@((message.ProfileId == Model.ProfileId) ? "right" : "") direct-chat-msg">
                            <input type="hidden" class="messageId" id="@message.Id" value="@message.Id" />

                            <div class="direct-chat-infos clearfix" style="@((message.ProfileId == Model.ProfileId) ? "margin-left:50%;" : "margin-right:50%;")">
                                <a class="direct-chat-name float-left" asp-controller="Profile" asp-action="UserProfile" asp-route-id="@message.ProfileId">
                                    @message.ProfileName
                                </a>
                                <span class="direct-chat-timestamp float-right">@message.CreatedOn</span>
                            </div>

                            <div class="direct-chat-text">
                                @message.Text
                            </div>
                        </div>
                    }
                </div>
            </div>

            <div class="card-footer">
                <div class="input-group">
                    <input id="message" type="text" class="form-control" placeholder="Message...">
                    <span class="input-group-append">
                        <button id="sendButton" class="btn btn-primary">Send</button>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>

@section Scripts{
<script>
    "use strict";

    var connection = new signalR.HubConnectionBuilder().withUrl("/chat").build();

    connection.start().then(function () {
        var groupId = String('@Model.Id');
        connection.invoke("ConnectToChat", groupId).catch(function (err) {
            return console.error(err.toString());
        });
    }).catch(function (err) {
        return console.error(err.toString());
    });

    connection.on("RecieveMessage",
        function (messageModel) {
            var currentProfileId = String('@Model.ProfileId');

            var message = `An unexpected Error has occured`;

            if (currentProfileId == messageModel.profileId) {
                message =
                    `
                    <div class="direct-chat-msg right">
                        <input type="hidden" class="messageId" id="${messageModel.id}" value="${messageModel.id}" />

                            <div class="direct-chat-infos clearfix" style="margin-left:50%;">
                                <a class="direct-chat-name float-left" asp-controller="Profile" asp-action="UserProfile" asp-route-id="${messageModel.profileId}">
                                    ${messageModel.profileName}
                                </a>
                                <span class="direct-chat-timestamp float-right">${messageModel.createdOn}</span>
                            </div>

                        <div class="direct-chat-text">
                            ${messageModel.text}
                        </div>
                    </div>
                    `;
            }
            else {
                message =
                    `
                    <div class="direct-chat-msg">
                        <input type="hidden" class="messageId" id="${messageModel.id}" value="${messageModel.id}" />

                            <div class="direct-chat-infos clearfix" style="margin-right:50%;">
                                <a class="direct-chat-name float-left" asp-controller="Profile" asp-action="UserProfile" asp-route-id="${messageModel.profileId}">
                                    ${messageModel.profileName}
                                </a>
                                <span class="direct-chat-timestamp float-right">${messageModel.createdOn}</span>
                            </div>

                        <div class="direct-chat-text">
                            ${messageModel.text}
                        </div>
                    </div>
                    `;
            }


            $(".direct-chat-messages").append(message);
        });


    $("#sendButton").click(function () {
        var message = String(document.getElementById("message").value);
        var groupId = String('@Model.Id');
        connection.invoke("Send", groupId, message).catch(function (err) {
            return console.error(err.toString());
        });
        $("#message").val("")
    });
</script>
}

FasterMate/Views/Group/Members.cshtml
@model GroupMemberViewModel
@{
    ViewData["Title"] = "Group Members";
}

<h2 class="text-center display-4 mt-2">Members of the group</h2>

<a class="btn btn-primary btn-lg btn-block mt-1" asp-route-id="@Model.Id" asp-action="AddMember" asp-controller="Group">Add members!</a>
@if (@Model.Members.Count() == 0)
{
    <h2 class="text-center display-4 mt-2">This group does not exist!!!</h2>
}
else
{
    @foreach (var member in @Model.Members)
    {
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="card card-widget widget-user mt-2">

                    <div class="widget-user-header bg-primary">
                        <a asp-action="UserProfile" asp-controller="Profile" asp-route-id="@member.ProfileId" class="widget-user-username">@member.Name</a>
                        <h5 class="widget-user-desc">&commat;@member.Username</h5>
                    </div>
                    <div class="widget-user-image">
                        @if (!string.IsNullOrWhiteSpace(member.ImagePath))
                        {
                            <img class="profile-user-img img-fluid img-circle" src="~/img/users/@member.ImagePath" alt="User profile picture">
                        }
                        else
                        {
                            <img class="profile-user-img img-fluid img-circle" src="~/img/common/default-male.png" alt="User profile picture">
                        }
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="description-block">
                                    @if (member.IsOwner)
                                    {
                                        <h5 class="description-header">Owner</h5>
                                    }
                                    else
                                    {
                                        <h5 class="description-header">Member</h5>

                                        <form method="post">
                                            <button class="btn btn-danger btn-block my-3" asp-controller="Group" asp-action="RemoveMember" asp-route-id="@Model.Id" asp-route-removeId="@member.ProfileId">
                                                <i class="fas fa-trash">
                                                </i>

                                                Remove member
                                            </button>
                                        </form>
                                    }
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    }
}

FasterMate/Views/Group/MyGroups.cshtml
@model IEnumerable<ProfileGroupsViewModel>
@{
    ViewData["Title"] = "My Groups";
}

<h1 class="text-center display-3">My Groups</h1>

<a asp-controller="Group" asp-action="Create" class="btn btn-primary btn-lg btn-block mt-1">Create New Group</a>

@if (Model.Count() > 0)
{
    <div class="card mt-2">
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 40%">
                            Group Name
                        </th>
                        <th style="width: 20%">
                            Group Image
                        </th>
                        <th style="width: 40%">

                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var group in Model)
                    {
                        <tr>
                            <td>
                                <a>
                                    <h2 class="display-5">
                                        @group.Name
                                    </h2>
                                </a>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <img src="~/img/groups/@group.ImagePath" alt="Avatar" class="rounded" width="150" height="150">
                                    </li>
                                </ul>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary" asp-controller="Group" asp-action="LetsChat" asp-route-id="@group.Id">
                                    <i class="fas fa-comments">
                                    </i>

                                    Chat
                                </a>
                                @if (group.IsOwner)
                                {
                                    <a class="btn btn-info" asp-controller="Group" asp-action="Members" asp-route-id="@group.Id">
                                        <i class="fas fa-users">
                                        </i>

                                        Members
                                    </a>
                                }
                                @if (group.IsOwner)
                                {
                                    <a class="btn btn-info" asp-controller="Group" asp-action="Edit" asp-route-id="@group.Id">
                                        <i class="fas fa-pencil-alt">
                                        </i>

                                        Edit Group
                                    </a>
                                }
                                @if (group.IsOwner)
                                {
                                    <form method="post">
                                        <button class="btn btn-danger mt-1" asp-controller="Group" asp-action="Delete" asp-route-id="@group.Id">
                                            <i class="fas fa-trash">
                                            </i>

                                            Delete Group
                                        </button>
                                    </form>
                                }
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
}
else
{
    <h2 class="mt-3 text-center">You aren't in any groups</h2>
}